# COMPOSE_BAKE=true docker compose -f compose.local.yml --env-file .env.development up -d --build
# COMPOSE_BAKE=true docker compose -f compose.local.yml --env-file .env.development down
services:
  server:
    image: server_local
    container_name: server
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.local
    env_file:
      - .env.development
    volumes:
      - ./src:/app/src
    ports:
      - '3001:3001'
    depends_on:
      - postgres
      - redis
    networks:
      - flashease

  postgres:
    image: postgres:17.4
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - flashease

  redis:
    image: redis/redis-stack:6.2.6-v17
    container_name: redis
    restart: unless-stopped
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - redis:/data
    environment:
      REDIS_ARGS: '--user default off --user ${REDIS_USERNAME} on >${REDIS_PASSWORD} ${REDIS_PERMISSIONS}'
    networks:
      - flashease

volumes:
  postgres:
  redis:

networks:
  flashease:
    external: true
